name: OTE Testing

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      URL: http://localhost:8080
      SELENIUM_URL: http://localhost:4444

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Create isolated network
        run: docker network create --driver bridge isolated

      - name: Build AUT image
        run: docker build -t my-php-site:latest .

      - name: Run AUT container
        run: docker run -d --network=isolated -p 8080:80 --name docker-apache my-php-site:latest

      - name: Check AUT Url
        run: curl -i ${{ env.URL }} | head -n 30

      - name: Selenium Preparation
        run: docker run --network=isolated -d -p 4444:4444 -p 7900:7900 -v /dev/shm:/dev/shm --name firefox-standalone selenium/standalone-firefox:latest

      - name: Wait for Selenium Hub
        run: sh wait.sh

      - name: Check the Hub
        run: curl http://localhost:4444/ui

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Selenium
        run: pip install -U selenium

      - name: Run test
        run: python tests/hello_aut.py ${{ env.URL }}

      - name: Stop docker
        if: always()
        run: |
          docker stop firefox-standalone || true
          docker stop docker-apache || true
